################################# Default configuration ###################
# provide your domain here
baseURL = "https://examplesite.com/"
# theme
theme = "dot"
# site title
title = "Centre de documentation"
description = "Ce site est le centre de documentation du SIPf à destination des développeurs."
# default language
defaultContentLanguage = 'fr'
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)

# unsafe html
[markup.goldmark.renderer]
unsafe= true

################################# navigation ################################
[[menu.main]]
name = "Nos référentiels"
url = "referentiels"
weight = 1

[[menu.main]]
name = "Nos APIs"
url = "https://developer.gov.pf"
weight = 2

[[menu.main]]
name = "Contribuez !"
url = "https://github.com/govpf/helpme"
weight = 3

#[[menu.main]]
#name = "Faq"
#url = "faq"
#weight = 2

#[[menu.main]]
#name = "contact"
#url = "contact"
#weight = 3

## Dropdown menu
#[[menu.main]]
#weight = 4
#name = "docs"
#hasChildren = true

#  [[menu.main]]
#  parent = "docs"
#  name = "Installation"
#  url = "installation"
#  weight = 1

#  [[menu.main]]
#  parent = "docs"
#  name = "Billing and Pricing"
#  url = "billing-pricing"
#  weight = 2

#  [[menu.main]]
#  parent = "docs"
#  name = "Features"
#  url = "features"
#  weight = 3


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#02007e"
#primary_color = "#F2C94C"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
#[[params.social]]
#icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
#link = "#"

[[params.social]]
icon = "ti-layout-grid4-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://www.service-public.pf"

[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "https://github.com/govpf"

################################ English Language ######################
##[Languages.en]
##languageName = "En"
##languageCode = "en-us"
##weight = 2
##home = "Home"
##copyright = "[SIPf](https://www.service-public.pf/sipf) @2021."

# banner
##[Languages.en.params.banner]
##title = "Support Center & Knowledge base"
##subtitle = "Find advice and answers from our support team fast or get in touch"
##bg_image = "images/banniere3.png"
##placeholder = "Have a question? Just ask here or enter terms"

# call to action
##[Languages.en.params.cta]
##enable = true
##title = "Didn't find an answer to your question?"
##content = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."
# call to action button
##[Languages.en.params.cta.button]
##enable = true
##label = "contact us"
##link = "contact"


################################### Franch Language ######################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
weight = 1
home = "Accueil"
copyright = "developer@administration.gov.pf - [SIPf](https://www.service-public.pf/sipf) @2021."

# banner
[Languages.fr.params.banner]
title = "Comment pouvons nous vous aider ?"
subtitle = "Ce site est à destination des agents oeuvrant pour la mise en oeuvre de service numérique pour la Polynésie française."
bg_image = "images/banniere3.png"
placeholder = "Vous avez une question ? Recherchez ici en saisissant des termes"

# call to action
[Languages.fr.params.cta]
enable = false
title = "Vous n'avez pas trouvé de réponse à votre question ?"
content = "Posez la nous directement en cliquant sur le bouton \"Contactez-nous\" !"

# call to action button
[Languages.fr.params.cta.button]
enable = false
label = "Contactez nous"
link = "contact"